// src/components/TableCell/TableCell.vue
<template>
  <td class="table__cell" :class="align">{{ data }}</td>
</template>

<script>
export default {
  props: {
    cellData: [String, Boolean, Number],
    type: String,
    colAlign: [String, undefined],
  },
  data() {
    return {
      align: this.colAlign,
      data: this.cellData,
    };
  },
  mounted() {
    if (this.type === "boolean") {
      this.data = this.cellData ? "Завершен" : "В процессе";
    }
    if (this.colAlign) {
      return;
    } else if (this.type === "float" || this.type === "number") {
      this.align = "right";
    } else if (this.type === "boolean") {
      this.align = "center";
    }
  },
};
</script>

// src/components/TableCell/TableCell.jsx
import { useEffect, useState } from "react";

function TableCell({ cellData, type, colAlign }) {
  const [align, setAlign] = useState("");
  const [data, setData] = useState(cellData);

  useEffect(() => {
    if (colAlign) {
      setAlign(colAlign);
    } else if (type === "float" || type === "number") {
      setAlign("right");
    } else if (type === "boolean") {
      setAlign("center");
    } else {
      setAlign("left");
    }
    if (type === "boolean") {
      setData(cellData ? "Завершен" : "В процессе");
    }
  }, [type, colAlign]);

  return (
    <>
      <td className={`table__cell ${align}`}>{data}</td>
    </>
  );
}

export default TableCell;
