// src/components/Select/Select.vue
<template>
  <select
    name="tableSelect"
    @change="$emit('changeTable', $event.target.value)"
  >
    <option :value="name" :key="i" v-for="(name, i) in tableNames">
      {{ name }}
    </option>
  </select>
</template>

<script>
export default {
  props: {
    tableNames: Array,
    tableChange: Function,
  },
};
</script>

// src/components/Select/Select.jsx
function Select({ tableNames, tableChange }) {
  function changeHandler({ target }) {
    tableChange(target.value);
  }

  return (
    <select name="tableSelect" onInput={changeHandler}>
      {tableNames.map((name, i) => (
        <option value={name} key={name + i}>
          {name}
        </option>
      ))}
    </select>
  );
}

export default Select;
