// src/components/TableRow/TableRow.jsx
import TableCell from "../TableCell/TableCell";

function TableRow({ rowData, headerInfo }) {
  return (
    <tr className="table__row">
      {rowData.map((cellData, i) => (
        <TableCell
          cellData={cellData.d || cellData}
          colAlign={headerInfo[i].align}
          type={headerInfo[i].type}
          key={headerInfo[i].id + cellData + i}
        />
      ))}
    </tr>
  );
}

export default TableRow;

// src/components/TableRow/TableRow.vue
<template>
  <tr class="table__row">
    <TableCell
      :cellData="cellData.d || cellData"
      :colAlign="headerInfo[i].align"
      :type="headerInfo[i].type"
      :key="generateKey(headerInfo[i].id, cellData, index)"
      v-for="(cellData, i) in rowData"
    />
  </tr>
</template>
;

<script>
import TableCell from "../TableCell/TableCell.vue";

export default {
  props: {
    rowData: Array,
    headerInfo: Object,
    index: Number,
  },
  components: { TableCell },
  methods: {
    generateKey(id, data, index) {
      const key = id + data + index;
      return key;
    },
  },
};
</script>
;
